// <auto-generated />
namespace Finance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class despesaetipodespesa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(despesaetipodespesa));
        
        string IMigrationMetadata.Id
        {
            get { return "202112041921241_despesa e tipo despesa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
